version: "3"

services:
  depdb:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=prodcongeladosdb
    volumes:
     - ./prodcongeladosdb.sql:/docker-entrypoint-initdb.d/1.script.sql